import { Geist, Geist_Mono } from "next/font/google";
import { ReactNode } from "react";
import { ToastContainer, Zoom } from "react-toastify";
import { AuthProvider } from "./Providers";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ToastContainer closeButton transition={Zoom} theme="dark" hideProgressBar />
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
